//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Project.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERACCOUNT
    {
        public int userid { get; set; }
        public string username { get; set; }
        public string userpassword { get; set; }
        public Nullable<int> ROLEID { get; set; }
        public Nullable<int> idnumber { get; set; }
    }
}
